spring.application.name=notifiche
# Nome dell'applicazione
spring.application.name=notifiche

# Configurazione del database in memoria H2
spring.datasource.url=jdbc:h2:mem:csirtdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Abilita la console web di H2 per vedere i dati dal browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate creerà/aggiornerà automaticamente le tabelle in base alle nostre classi Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true